// ........
function filterByPageAndLevel(dataArray) {
  let result = [];

  // Sắp xếp các mảng JSON theo thứ tự tăng dần của "page"
  dataArray.sort((a, b) => a.page - b.page);

  for (let data of dataArray) {
    let page = data.page;
    let customers = data.customers;

    // Lọc ra các khách hàng có "level" từ "Vip1" đến "Vip5" trong "customers"
    for (let key in customers) {
      let customer = customers[key];
      let level = customer.level;

      if (level && level.startsWith('Vip') && parseInt(level.slice(3)) >= 1 && parseInt(level.slice(3)) <= 5) {
        result.push({ page, customer }); // Thêm cả giá trị "page" vào kết quả
      }
    }
  }

  return result;
}function filterByPageAndLevel(dataArray) {
  let result = [];

  // Sắp xếp các mảng JSON theo thứ tự tăng dần của "page"
  dataArray.sort((a, b) => a.page - b.page);

  for (let data of dataArray) {
    let page = data.page;
    let customers = data.customers;

    // Lọc ra các khách hàng có "level" từ "Vip1" đến "Vip5" trong "customers"
    for (let key in customers) {
      let customer = customers[key];
      let level = customer.level;

      if (level && level.startsWith('Vip') && parseInt(level.slice(3)) >= 1 && parseInt(level.slice(3)) <= 5) {
        let filteredCustomer = {
          id: customer.id,
          name: customer.name,
          mobile: customer.mobile,
          level: customer.level,
          points: customer.points
        };
        result.push({ page, customer: filteredCustomer }); // Thêm cả giá trị "page" vào kết quả
      }
    }
  }

  return result;
}


// Các mảng JSON đầu vào (data) từ API
let jsonDataArray = [
  {
    "totalPages": 32149,
    "page": 1,
    "customers": {
            "10231372": {
                "id": "10231372",
                "type": "1",
                "name": "Vương Đức Lâm",
                "mobile": "0932447772",
                "gender": null,
                "email": null,
                "address": "124/4 Trần Kế Xương, phường 7, quận Phú Nhuận, TP. HCM",
                "birthday": null,
                "code": "KH85709",
                "level": "Vip5",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231373": {
                "id": "10231373",
                "type": "1",
                "name": "Vương Doanh",
                "mobile": "0986899326",
                "gender": null,
                "email": null,
                "address": "249 Thống Nhất ( mới ) - F8 - Tp. vũng tàu\tbà rịa",
                "birthday": null,
                "code": "KH35746",
                "level": "Vip1",
                "group": "VIP1",
                "levelId": "2031",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "180000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231374": {
                "id": "10231374",
                "type": "1",
                "name": "Vượng",
                "mobile": "0979709887",
                "gender": null,
                "email": null,
                "address": "28/60 Ngọc Hà",
                "birthday": null,
                "code": "KHC9053",
                "level": "Vip2",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "254",
                "districtLocationId": "318",
                "wardLocationId": "",
                "totalMoney": "0",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231381": {
                "id": "10231381",
                "type": "1",
                "name": "Vũ Tường Vân",
                "mobile": "0335483781",
                "gender": null,
                "email": null,
                "address": null,
                "birthday": null,
                "code": "KH61321",
                "level": "Vip3",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "1",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231382": {
                "id": "10231382",
                "type": "1",
                "name": "Anh Ngân",
                "mobile": "0974137044",
                "gender": null,
                "email": null,
                "address": "18 ngõ 116 đại từ",
                "birthday": null,
                "code": "KH57828",
                "level": "Vip2",
                "group": "VIP1",
                "levelId": "2032",
                "groupId": "1228",
                "cityLocationId": "254",
                "districtLocationId": "317",
                "wardLocationId": "1158",
                "totalMoney": "1965000",
                "startedDate": "2018-04-12",
                "startedDepotId": "17999",
                "points": 0,
                "totalBills": "7",
                "lastBoughtDate": "2021-12-27",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231383": {
                "id": "10231383",
                "type": "1",
                "name": "Vũ Trung Kiên",
                "mobile": "0969020697",
                "gender": null,
                "email": null,
                "address": "39 Nguyễn Văn Trỗi-Hà Đông-Hà Nội",
                "birthday": null,
                "code": "KH26270",
                "level": "Vip4",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231384": {
                "id": "10231384",
                "type": "1",
                "name": "Vũ Trung Dũng",
                "mobile": "0357116114",
                "gender": null,
                "email": null,
                "address": "303 nhà B ngõ 805 đường giải phóng,giáp bát,hoàng mai,hà nội",
                "birthday": null,
                "code": "KH34594",
                "level": "",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "50000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            }}
  },
  {
    "totalPages": 32149,
    "page": 2,
    "customers": {
            "10231372": {
                "id": "10231372",
                "type": "1",
                "name": "Vương Đức Lâm",
                "mobile": "0932447772",
                "gender": null,
                "email": null,
                "address": "124/4 Trần Kế Xương, phường 7, quận Phú Nhuận, TP. HCM",
                "birthday": null,
                "code": "KH85709",
                "level": "Vip5",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231373": {
                "id": "10231373",
                "type": "1",
                "name": "Vương Doanh",
                "mobile": "0986899326",
                "gender": null,
                "email": null,
                "address": "249 Thống Nhất ( mới ) - F8 - Tp. vũng tàu\tbà rịa",
                "birthday": null,
                "code": "KH35746",
                "level": "Vip1",
                "group": "VIP1",
                "levelId": "2031",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "180000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231374": {
                "id": "10231374",
                "type": "1",
                "name": "Vượng",
                "mobile": "0979709887",
                "gender": null,
                "email": null,
                "address": "28/60 Ngọc Hà",
                "birthday": null,
                "code": "KHC9053",
                "level": "Vip2",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "254",
                "districtLocationId": "318",
                "wardLocationId": "",
                "totalMoney": "0",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231381": {
                "id": "10231381",
                "type": "1",
                "name": "Vũ Tường Vân",
                "mobile": "0335483781",
                "gender": null,
                "email": null,
                "address": null,
                "birthday": null,
                "code": "KH61321",
                "level": "Vip3",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "1",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231382": {
                "id": "10231382",
                "type": "1",
                "name": "Anh Ngân",
                "mobile": "0974137044",
                "gender": null,
                "email": null,
                "address": "18 ngõ 116 đại từ",
                "birthday": null,
                "code": "KH57828",
                "level": "Vip2",
                "group": "VIP1",
                "levelId": "2032",
                "groupId": "1228",
                "cityLocationId": "254",
                "districtLocationId": "317",
                "wardLocationId": "1158",
                "totalMoney": "1965000",
                "startedDate": "2018-04-12",
                "startedDepotId": "17999",
                "points": 0,
                "totalBills": "7",
                "lastBoughtDate": "2021-12-27",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231383": {
                "id": "10231383",
                "type": "1",
                "name": "Vũ Trung Kiên",
                "mobile": "0969020697",
                "gender": null,
                "email": null,
                "address": "39 Nguyễn Văn Trỗi-Hà Đông-Hà Nội",
                "birthday": null,
                "code": "KH26270",
                "level": "Vip4",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231384": {
                "id": "10231384",
                "type": "1",
                "name": "Vũ Trung Dũng",
                "mobile": "0357116114",
                "gender": null,
                "email": null,
                "address": "303 nhà B ngõ 805 đường giải phóng,giáp bát,hoàng mai,hà nội",
                "birthday": null,
                "code": "KH34594",
                "level": "",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "50000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            }}
  },
  {
    "totalPages": 32149,
    "page": 3,
    "customers": {
            "10231372": {
                "id": "10231372",
                "type": "1",
                "name": "Vương Đức Lâm",
                "mobile": "0932447772",
                "gender": null,
                "email": null,
                "address": "124/4 Trần Kế Xương, phường 7, quận Phú Nhuận, TP. HCM",
                "birthday": null,
                "code": "KH85709",
                "level": "Vip5",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231373": {
                "id": "10231373",
                "type": "1",
                "name": "Vương Doanh",
                "mobile": "0986899326",
                "gender": null,
                "email": null,
                "address": "249 Thống Nhất ( mới ) - F8 - Tp. vũng tàu\tbà rịa",
                "birthday": null,
                "code": "KH35746",
                "level": "Vip1",
                "group": "VIP1",
                "levelId": "2031",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "180000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231374": {
                "id": "10231374",
                "type": "1",
                "name": "Vượng",
                "mobile": "0979709887",
                "gender": null,
                "email": null,
                "address": "28/60 Ngọc Hà",
                "birthday": null,
                "code": "KHC9053",
                "level": "Vip2",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "254",
                "districtLocationId": "318",
                "wardLocationId": "",
                "totalMoney": "0",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231381": {
                "id": "10231381",
                "type": "1",
                "name": "Vũ Tường Vân",
                "mobile": "0335483781",
                "gender": null,
                "email": null,
                "address": null,
                "birthday": null,
                "code": "KH61321",
                "level": "Vip3",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "1",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231382": {
                "id": "10231382",
                "type": "1",
                "name": "Anh Ngân",
                "mobile": "0974137044",
                "gender": null,
                "email": null,
                "address": "18 ngõ 116 đại từ",
                "birthday": null,
                "code": "KH57828",
                "level": "Vip2",
                "group": "VIP1",
                "levelId": "2032",
                "groupId": "1228",
                "cityLocationId": "254",
                "districtLocationId": "317",
                "wardLocationId": "1158",
                "totalMoney": "1965000",
                "startedDate": "2018-04-12",
                "startedDepotId": "17999",
                "points": 0,
                "totalBills": "7",
                "lastBoughtDate": "2021-12-27",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231383": {
                "id": "10231383",
                "type": "1",
                "name": "Vũ Trung Kiên",
                "mobile": "0969020697",
                "gender": null,
                "email": null,
                "address": "39 Nguyễn Văn Trỗi-Hà Đông-Hà Nội",
                "birthday": null,
                "code": "KH26270",
                "level": "Vip4",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231384": {
                "id": "10231384",
                "type": "1",
                "name": "Vũ Trung Dũng",
                "mobile": "0357116114",
                "gender": null,
                "email": null,
                "address": "303 nhà B ngõ 805 đường giải phóng,giáp bát,hoàng mai,hà nội",
                "birthday": null,
                "code": "KH34594",
                "level": "",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "50000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            }}
  },
  {
    "totalPages": 32149,
    "page": 4,
    "customers": {
            "10231372": {
                "id": "10231372",
                "type": "1",
                "name": "Vương Đức Lâm",
                "mobile": "0932447772",
                "gender": null,
                "email": null,
                "address": "124/4 Trần Kế Xương, phường 7, quận Phú Nhuận, TP. HCM",
                "birthday": null,
                "code": "KH85709",
                "level": "Vip5",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231373": {
                "id": "10231373",
                "type": "1",
                "name": "Vương Doanh",
                "mobile": "0986899326",
                "gender": null,
                "email": null,
                "address": "249 Thống Nhất ( mới ) - F8 - Tp. vũng tàu\tbà rịa",
                "birthday": null,
                "code": "KH35746",
                "level": "Vip1",
                "group": "VIP1",
                "levelId": "2031",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "180000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231374": {
                "id": "10231374",
                "type": "1",
                "name": "Vượng",
                "mobile": "0979709887",
                "gender": null,
                "email": null,
                "address": "28/60 Ngọc Hà",
                "birthday": null,
                "code": "KHC9053",
                "level": "Vip2",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "254",
                "districtLocationId": "318",
                "wardLocationId": "",
                "totalMoney": "0",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231381": {
                "id": "10231381",
                "type": "1",
                "name": "Vũ Tường Vân",
                "mobile": "0335483781",
                "gender": null,
                "email": null,
                "address": null,
                "birthday": null,
                "code": "KH61321",
                "level": "Vip3",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "1",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231382": {
                "id": "10231382",
                "type": "1",
                "name": "Anh Ngân",
                "mobile": "0974137044",
                "gender": null,
                "email": null,
                "address": "18 ngõ 116 đại từ",
                "birthday": null,
                "code": "KH57828",
                "level": "Vip2",
                "group": "VIP1",
                "levelId": "2032",
                "groupId": "1228",
                "cityLocationId": "254",
                "districtLocationId": "317",
                "wardLocationId": "1158",
                "totalMoney": "1965000",
                "startedDate": "2018-04-12",
                "startedDepotId": "17999",
                "points": 0,
                "totalBills": "7",
                "lastBoughtDate": "2021-12-27",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231383": {
                "id": "10231383",
                "type": "1",
                "name": "Vũ Trung Kiên",
                "mobile": "0969020697",
                "gender": null,
                "email": null,
                "address": "39 Nguyễn Văn Trỗi-Hà Đông-Hà Nội",
                "birthday": null,
                "code": "KH26270",
                "level": "Vip4",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231384": {
                "id": "10231384",
                "type": "1",
                "name": "Vũ Trung Dũng",
                "mobile": "0357116114",
                "gender": null,
                "email": null,
                "address": "303 nhà B ngõ 805 đường giải phóng,giáp bát,hoàng mai,hà nội",
                "birthday": null,
                "code": "KH34594",
                "level": "",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "50000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            }}
  },
  {
    "totalPages": 32149,
    "page": 5,
    "customers": {
            "10231372": {
                "id": "10231372",
                "type": "1",
                "name": "Vương Đức Lâm",
                "mobile": "0932447772",
                "gender": null,
                "email": null,
                "address": "124/4 Trần Kế Xương, phường 7, quận Phú Nhuận, TP. HCM",
                "birthday": null,
                "code": "KH85709",
                "level": "Vip5",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231373": {
                "id": "10231373",
                "type": "1",
                "name": "Vương Doanh",
                "mobile": "0986899326",
                "gender": null,
                "email": null,
                "address": "249 Thống Nhất ( mới ) - F8 - Tp. vũng tàu\tbà rịa",
                "birthday": null,
                "code": "KH35746",
                "level": "Vip1",
                "group": "VIP1",
                "levelId": "2031",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "180000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231374": {
                "id": "10231374",
                "type": "1",
                "name": "Vượng",
                "mobile": "0979709887",
                "gender": null,
                "email": null,
                "address": "28/60 Ngọc Hà",
                "birthday": null,
                "code": "KHC9053",
                "level": "Vip2",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "254",
                "districtLocationId": "318",
                "wardLocationId": "",
                "totalMoney": "0",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231381": {
                "id": "10231381",
                "type": "1",
                "name": "Vũ Tường Vân",
                "mobile": "0335483781",
                "gender": null,
                "email": null,
                "address": null,
                "birthday": null,
                "code": "KH61321",
                "level": "Vip3",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "1",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231382": {
                "id": "10231382",
                "type": "1",
                "name": "Anh Ngân",
                "mobile": "0974137044",
                "gender": null,
                "email": null,
                "address": "18 ngõ 116 đại từ",
                "birthday": null,
                "code": "KH57828",
                "level": "Vip2",
                "group": "VIP1",
                "levelId": "2032",
                "groupId": "1228",
                "cityLocationId": "254",
                "districtLocationId": "317",
                "wardLocationId": "1158",
                "totalMoney": "1965000",
                "startedDate": "2018-04-12",
                "startedDepotId": "17999",
                "points": 0,
                "totalBills": "7",
                "lastBoughtDate": "2021-12-27",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231383": {
                "id": "10231383",
                "type": "1",
                "name": "Vũ Trung Kiên",
                "mobile": "0969020697",
                "gender": null,
                "email": null,
                "address": "39 Nguyễn Văn Trỗi-Hà Đông-Hà Nội",
                "birthday": null,
                "code": "KH26270",
                "level": "Vip4",
                "group": "VIP1",
                "levelId": "",
                "groupId": "1228",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "90000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            },
            "10231384": {
                "id": "10231384",
                "type": "1",
                "name": "Vũ Trung Dũng",
                "mobile": "0357116114",
                "gender": null,
                "email": null,
                "address": "303 nhà B ngõ 805 đường giải phóng,giáp bát,hoàng mai,hà nội",
                "birthday": null,
                "code": "KH34594",
                "level": "",
                "group": "",
                "levelId": "",
                "groupId": "",
                "cityLocationId": "",
                "districtLocationId": "",
                "wardLocationId": "",
                "totalMoney": "50000",
                "startedDate": "2017-11-02",
                "startedDepotId": "",
                "points": 0,
                "totalBills": "0",
                "lastBoughtDate": "",
                "taxCode": "",
                "businessName": "",
                "businessAddress": "",
                "description": ""
            }}
  }
];

// Sử dụng function và log kết quả
let filteredData = filterByPageAndLevel(jsonDataArray);
console.log(filteredData);